python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 0 > log0.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 1 > log1.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 2 > log2.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 3 > log3.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 4 > log4.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 5 > log5.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 6 > log6.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 7 > log7.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 8 > log8.txt
python3 -m qlearn.toys.main_nchain --agent BootstrappedDQN --cuda 0 --input-dim 100 --double-q 0 --ucb 0 --max-episodes 2000 --plot_states 0 --seed 9 > log9.txt
